### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/kamelmat-Random-Card-Generator#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- Muy buen trabajo @kamelmat . Felicitaciones 🥳
## Estilo de código y limpieza
- ¡Buen trabajo!
## Mejores prácticas/comentarios
- Muy bien resuelto... sólo comentarte que en el `setInterval` le has puesto un valor de 10000 (es decir, un minuto), no sé si te equivocaste y querías poner 1000 (un segundo)
![Captura de pantalla de 2024-04-10 11-26-37](https://github.com/4GeeksAcademy/kamelmat-Random-Card-Generator/assets/139759297/9ae9b9c9-d452-418c-bca2-74ed8f29e1fc)

**Comment by kamelmat** [comment]
### Gracias @EduardoHernandezGuzman  por los comments!
🤔 si no me equivoco, 10000 son milisegundos y equivalen a 10 segundos que si no leí mal, era el tiempo que pedía el contador.
